#!/bin/sh

DAEMON_SBIN=/usr/sbin/hostapd
DAEMON_CONF=/etc/hostapd.conf
NAME=hostapd
PIDFILE=/var/run/hostapd.pid

test -x "$DAEMON_SBIN"  || exit 0
test -r "$DAEMON_CONF"  || exit 0

DAEMON_OPTS="-B -P $PIDFILE $DAEMON_OPTS $DAEMON_CONF"

start() {
    printf "Starting $NAME: "
    umask 077
    start-stop-daemon -S -q -p "$PIDFILE" \
            --exec "$DAEMON_SBIN" -- $DAEMON_OPTS
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -p "$PIDFILE" \
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 8
    start
    ;;
  *)
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit $?
